### PR TITLE
memfd: fix build with glibc 2.27

### PR DESCRIPTION
**Pull request by baruchsiach**
glibc 2.27 added a wrapper for memfd_create(). This causes build
failure:

fds/memfd.c:19:12: error: static declaration of 'memfd_create' follows non-static declaration
 static int memfd_create(__unused__ const char *uname, __unused__ unsigned int flag)
            ^~~~~~~~~~~~

Don't use the local definition when the libc provides one.

Signed-off-by: Baruch Siach <baruch@tkos.co.il>

### CODE REVIEW

**Comment by kernelslacker** [comment]
lgtm. thanks
